name: ML Pipeline

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --index-url https://download.pytorch.org/whl/cpu torch torchvision
        pip install -r requirements.txt
    
    - name: Train model
      run: |
        python model.py
    
    - name: Run tests
      run: |
        pytest test_model.py -v
    
    - name: Upload trained model
      uses: actions/upload-artifact@v4
      with:
        name: trained-model
        path: mnist_model_*.pth
        retention-days: 90